[book]
title = "RootMe Solutions & Write-Ups"
authors = ["nh4ttruong"]
description = "RootMe Solutions & Write-Ups for education purposes."

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/nh4ttruong/emtoor"
git-repository-icon = "fa-github"
site-url = "/emtoor/"

[output.html.search]
limit-results = 15

[output.wordcount]
optional = true