[book]
title = "RootMe Solutions & Write-Up"
authors = ["nh4ttruong"]
description = "RootMe solutions & write-ups made for education. Hands‑on CTF guides, real hacking scenarios, and clear steps to level up your cyber skills. Let's dive into hacking!"

[build]
create-missing = false
build-dir = "./"

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/nh4ttruong/emtoor"
git-repository-icon = "fa-github"
site-url = "/emtoor/"
hash-files = true
additional-js = ["theme/js/medium-zoom.min.js", "theme/js/image-zoom.js"]
additional-css = ["theme/css/image-zoom.css"]
edit-url-template = "https://github.com/nh4ttruong/emtoor/edit/main/{path}"

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true           # include Javascript code for search

[output.html.playground]
copyable = true
editable = true

[output.html.fold]
enable = true

[output.wordcount]
optional = true