name: Deploy GitHub Pages

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - book
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Sync sources
        run: |
          chmod +x script/sync.sh
          bash script/sync.sh
        working-directory: ./book

      - name: Build site with mdbook
        run: mdbook build
        working-directory: ./book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/book'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
        working-directory: ./book