name: Deploy GitHub Pages

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install static-sitemap-cli
        run: npm install static-sitemap-cli

      - name: Set up mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Sync sources
        run: |
          chmod +x ci/sync.sh
          bash ci/sync.sh

      - name: Build site with mdbook
        run: mdbook build
        working-directory: ./book

      - name: Generate sitemap
        run: |
          npx sscli --no-clean -c '**,monthly' -m '**/*.{html,jpg,png}' -f xml --base https://nh4ttruong.github.io/emtoor
        working-directory: ./book/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html